use_frameworks!

target 'CreditCardEvaluator_Example' do
  pod 'CreditCardEvaluator', :path => '../'

  target 'CreditCardEvaluator_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.1.0'
    pod 'Nimble', '~> 8.0.1'
  end
end
